```{r}
# data prep
heart = read_csv("heart_disease.csv")

heart = heart %>% mutate(Sex = factor(Sex)) %>%
  mutate(ChestPainType = factor(ChestPainType))%>%
  mutate(RestingECG = factor(RestingECG))%>%
  mutate(ExerciseAngina = factor(ExerciseAngina))%>%
  mutate(ST_Slope = factor(ST_Slope))%>%
  mutate(HeartDisease = factor(HeartDisease))

heart = heart %>% mutate(HeartDisease = fct_recode(HeartDisease, "Yes" = "1", "No" = "0"))
```

```{r}
# Q1
set.seed(12345)
heart_split = initial_split(heart, prop = .7, strata = HeartDisease)
train = training(heart_split)
test = testing(heart_split)
nrow(train)
```

```{r}
# Q2
heart_recipe = recipe(HeartDisease ~ ., train)

tree_model = decision_tree() %>%
  set_engine("rpart", model = TRUE) %>%
  set_mode("classification")

heart_wflow =
  workflow() %>%
  add_model(tree_model) %>%
  add_recipe(heart_recipe)

heart_fit = fit(heart_wflow, train)


heart_fit %>%
  extract_fit_parsnip() %>%
  pluck("fit")

tree = heart_fit %>%
  pull_workflow_fit() %>%
  pluck("fit")

rpart.plot(tree)
```

```{r}
# Q3
heart_fit$fit$fit$fit$cptable
```

```{r}
# Q4
set.seed(123)
folds = vfold_cv(train, v = 5)

heart_recipe2 = recipe(HeartDisease ~ ., train)

tree_model2 = decision_tree(cost_complexity = tune()) %>%
  set_engine("rpart", model = TRUE) %>%
  set_mode("classification")

tree_grid2 = grid_regular(cost_complexity(), levels = 25)

heart_wflow2 = 
  workflow() %>%
  add_model(tree_model2) %>%
  add_recipe(heart_recipe2)

tree_res2 = 
  heart_wflow2 %>%
  tune_grid(
    resamples = folds,
    grid = tree_grid2
  )

tree_res2

tree_res2 %>%
  collect_metrics() %>%
  ggplot(aes(cost_complexity, mean)) +
  geom_line(size = 1.5, alpha = 0.6) +
  geom_point(size = 2) +
  facet_wrap(~ .metric, scales = "free", nrow = 2)
```

```{r}
# Q5
best_tree = tree_res2 %>%
  select_best(metric = "accuracy")

best_tree
```

```{r}
# Q6
final_wf =
  heart_wflow2 %>%
  finalize_workflow(best_tree)

final_fit = fit(final_wf, train)

tree = final_fit %>%
  pull_workflow_fit() %>%
  pluck("fit")

fancyRpartPlot(tree, tweak = 1.1)

treepred = predict(final_fit, train, type = "class")
```

```{r}
# Q7 & Q8
confusionMatrix(treepred$.pred_class, train$HeartDisease, positive = "Yes")
```

```{r}
# Q10
treepred2 = predict(final_fit, test, type = "class")

confusionMatrix(treepred2$.pred_class, test$HeartDisease, positive = "Yes")

(137+91)/276
```

